<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [42]:
# CODE HERE

import numpy as np
import torch

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [43]:
# CODE HERE

np.random.seed(42)
torch.manual_seed(42);

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [44]:
# CODE HERE

arr = np.random.randint(0, 5, 6)

arr

array([3, 4, 2, 4, 4, 1])

In [45]:
# DON'T WRITE HERE

### 4. Create a tensor "x" from the array above

In [46]:
# CODE HERE

x = torch.from_numpy(arr)

x

tensor([3, 4, 2, 4, 4, 1])

In [47]:
# DON'T WRITE HERE

### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [48]:
# CODE HERE

x = x.type(torch.int64)
print(x.type())

torch.LongTensor


In [49]:
# DON'T WRITE HERE

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [50]:
# CODE HERE

x = x.reshape(3,2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [51]:
# DON'T WRITE HERE

### 7. Return the right-hand column of tensor x

In [52]:
# CODE HERE

x[:, 1:]

tensor([[4],
        [4],
        [1]])

In [53]:
# DON'T WRITE HERE

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [54]:
# CODE HERE

x ** 2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [55]:
# DON'T WRITE HERE

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [56]:
# CODE HERE

y = torch.randint(0,5, (2,3))
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [ ]:
# DON'T WRITE HERE

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Find the matrix product of x and y

In [58]:
# CODE HERE

torch.mm(x, y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

In [ ]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Great job!