In [ ]:
import torch
import numpy as np

In [ ]:
torch.__version__

'2.2.1+cu121'

In [ ]:
arr = np.array([1,2,3,4,5])

arr

array([1, 2, 3, 4, 5])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# converting numpy array to a pytorch tensor

x = torch.from_numpy(arr)

In [ ]:
type(x)

torch.Tensor

In [ ]:
x = torch.as_tensor(arr)

In [ ]:
x.dtype

torch.int64

In [ ]:
arr2d = np.arange(0.0, 12.0)

In [ ]:
# reshaping

arr2d = arr2d.reshape(4,3)

In [ ]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
x2 = torch.from_numpy(arr2d)

In [ ]:
arr[0] = 99

arr

array([99,  2,  3,  4,  5])

In [ ]:
# from numpy method has a direct link to np array so is affected when you change original np array
x

tensor([99,  2,  3,  4,  5])

In [ ]:
my_arr = np.arange(0, 10)

In [ ]:
my_tensor = torch.tensor(my_arr)

In [ ]:
my_other_tensor = torch.from_numpy(my_arr)

In [ ]:
my_arr[0] = 999

In [ ]:
my_other_tensor

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
new_arr = np.array([1,2,3])

In [ ]:
new_arr.dtype

dtype('int64')

In [ ]:
# lowercase t infers dtype from the original object
torch.tensor(new_arr)

tensor([1, 2, 3])

In [ ]:
# capital T tensor converts to floating point
my_tensor = torch.Tensor(new_arr)

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
torch.empty(2,2)

tensor([[1.8394e+25, 5.0850e+31],
        [3.0354e+32, 6.5703e+05]])

In [ ]:
torch.zeros(4,3, dtype=torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(0, 18, 2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
my_tensor = torch.tensor([1,2,3])

In [ ]:
my_tensor.dtype

torch.int64

In [ ]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# 4 by 3 tensor of random samples from a uniform distribution of 0 to 1
torch.rand(4,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [ ]:
# standard normal distribution mean at 0 and std = 1
torch.randn(4,3)

tensor([[ 0.3930,  0.4327, -1.3627],
        [ 1.3564,  0.6688, -0.7077],
        [-0.3267, -0.2788, -0.4220],
        [-1.3323, -0.3639,  0.1513]])

In [ ]:
# random numbers between high of 10 and low of 0 (high is inclusive)
torch.randint(low=0, high=10, size=(5,5))

tensor([[7, 9, 7, 3, 3],
        [4, 3, 7, 0, 9],
        [0, 9, 6, 9, 5],
        [4, 8, 8, 6, 0],
        [0, 0, 0, 1, 3]])

In [ ]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
x.shape

torch.Size([2, 5])

In [ ]:
# random but keeps shape from incoming tensor
torch.rand_like(x)

tensor([[0.2036, 0.2018, 0.2018, 0.9497, 0.6666],
        [0.9811, 0.0874, 0.0041, 0.1088, 0.1637]])

In [ ]:
torch.randn_like(x)

tensor([[-0.6441, -0.6061, -0.1425,  0.9727,  2.0038],
        [ 0.6622,  0.5332,  2.7489, -0.3841, -1.9623]])

In [ ]:
torch.randint_like(x, low=0, high=11)

tensor([[ 4.,  7.,  0.,  8., 10.],
        [ 7.,  9., 10.,  2., 10.]])

In [ ]:
# setting a seed for reproducibility (easiest to have random tensor in same cell)
torch.manual_seed(42)

torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
# row, column indexing / slicing

x[1, 1]

tensor(3)

In [ ]:
x[:, 1]

tensor([1, 3, 5])

In [ ]:
# indexing for the column

x[:,1:]

tensor([[1],
        [3],
        [5]])

In [ ]:
x = torch.arange(10)

In [ ]:
# just viewing, not changing the underlying object

x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reassigns object in memory

x = x.reshape(2,5)

In [ ]:
x = torch.arange(10)

In [ ]:
x.shape

torch.Size([10])

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z = x.view(2,5)

In [ ]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x[0] = 999

In [ ]:
x

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
# z is attatched to x so is affected

z

tensor([[999,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [ ]:
x = torch.arange(10)

In [ ]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape

torch.Size([10])

In [ ]:
# pytorch infers what the second dimension should be with -1

x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [ ]:
a + b

tensor([5., 7., 9.])

In [ ]:
a.mul_(b)

# a = a * b

tensor([ 4., 10., 18.])

In [ ]:
# underscore operator reassings value

a

tensor([ 4., 10., 18.])

In [ ]:
a.dot(b)

tensor(174.)

In [ ]:
a = torch.tensor([[0,2,4], [1,3,5]])
b = torch.tensor([[6,7], [8,9], [10,11]])

In [ ]:
a.shape

torch.Size([2, 3])

In [ ]:
b.shape

torch.Size([3, 2])

In [ ]:
# matrix multiplication

torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [ ]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [ ]:
x = torch.tensor([2,3,4,5], dtype = torch.float)

In [ ]:
# euclidian norm

x.norm()

tensor(7.3485)

In [ ]:
# number of elements

x.numel()

4

In [ ]:
len(x)

4

In [ ]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
len(a)

2

In [ ]:
a.numel()

6