#Tensor Basics

In [1]:
import tensorflow as tf

In [6]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
tensor_one_d = tf.constant([2, 0, -3, 8, 90])
print(tensor_one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [9]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])

print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [10]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
     [4,-3,32]],

])

In [11]:
# can do a 4-D array by stacking 3-D arrays

In [22]:
# messing with the datatypes

tensor_one_d = tf.constant([2, 0, -3, 8, 90], dtype=tf.float32)

casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.int16)
casted_tensor_one_d_bool = tf.cast(tensor_one_d, dtype=tf.bool)

tensor_bool = tf.constant([True, True, False])

tensor_string = tf.constant(['Hello world', 'hi'])

print(tensor_one_d)
print(casted_tensor_one_d)
print(casted_tensor_one_d_bool)
print(tensor_bool)
print(tensor_string)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)
tf.Tensor([b'Hello world' b'hi'], shape=(2,), dtype=string)


In [23]:
# converting numpy arrays into tensors

import numpy as np

In [24]:
np_array = np.array([1,2,4])

In [25]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [33]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns = None,
    batch_shape = [2,] ,
    dtype = tf.dtypes.float16, #can be set to anything
    name = None,
)

print(eye_tensor)
print(3 * eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float16)
tf.Tensor(
[[[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]
  [0. 0. 0. 3. 0.]
  [0. 0. 0. 0. 3.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]
  [0. 0. 0. 3. 0.]
  [0. 0. 0. 0. 3.]]], shape=(2, 5, 5), dtype=float16)


In [36]:
fill_tensor = tf.fill(
    [1, 3,4],5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [40]:
# creates a tensor with all values set to one

ones_tensor = tf.ones(
    [5,3],
    dtype = tf.dtypes.float32,
    name = None
)

print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [44]:
# creates a tensor of all ones that has the same shape as the input

tensor_ones_like = tf.ones_like(fill_tensor)
print(tensor_ones_like)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [47]:
# all elements set to zero

zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)

print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [49]:
# returns a tensor that has the shape of the input tensor

print(tf.shape(zeros_tensor))

tf.Tensor([3 2], shape=(2,), dtype=int32)


In [53]:
# rank / size

t = tf.constant([[1,2,3], [1,1,1]])
print(tf.rank(t))
print(tf.size(t))

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [54]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [55]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [56]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [60]:
# generating randoms using tf
# outputs random values from a normal distribution

random_tensor = tf.random.normal(
    [3,2],
    mean=100,
    stddev=1.0,
    dtype = tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 99.81157  101.00209 ]
 [100.18729  100.256325]
 [ 99.02961  102.38209 ]], shape=(3, 2), dtype=float32)


In [68]:
random_t = tf.random.uniform(
    [5,5],
    minval = 0,
    maxval = 1000,
    dtype = tf.dtypes.int32,
    seed = None,
    name = None,
)

print(random_t)

tf.Tensor(
[[130 776   8 603  76]
 [453  66 216 731 331]
 [698 503 846 568 913]
 [187 724 231 359 477]
 [215 524 138 512 844]], shape=(5, 5), dtype=int32)


In [70]:
# setting a seed for reproducability

tf.random.set_seed(5) # global seed
random_t_seed = tf.random.uniform(
    [5,6],
    minval = 0,
    maxval = 1000,
    dtype = tf.dtypes.int32,
    seed = 10,
    name = None,
)
print(random_t_seed)

tf.Tensor(
[[439 703 716 183 845 486]
 [662 328 131 108 389 106]
 [880 436 712 439 758 740]
 [514 804   0 853 839 385]
 [409 988 192 743 578 137]], shape=(5, 6), dtype=int32)


In [71]:
tf.random.set_seed(5) # global seed
random_t_seed = tf.random.uniform(
    [5,6],
    minval = 0,
    maxval = 1000,
    dtype = tf.dtypes.int32,
    seed = 10,
    name = None,
)
print(random_t_seed) #same output bc of seed

tf.Tensor(
[[439 703 716 183 845 486]
 [662 328 131 108 389 106]
 [880 436 712 439 758 740]
 [514 804   0 853 839 385]
 [409 988 192 743 578 137]], shape=(5, 6), dtype=int32)


#Tensor Slicing

In [77]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed)
print(tensor_indexed[:4])



tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


In [95]:
tensor_indexed_two_d = tf.constant([
    [1,2,3],
    [1,2,4],
    [4,7,9],
    [2,3,8]
])

# print(tf.shape(tensor_indexed_two_d))
print(tensor_indexed_two_d[0,2]) #left side represents rows, right side represents columns
print(tensor_indexed_two_d[0:3, 2])
print(tensor_indexed_two_d[:,1])
print(tensor_indexed_two_d[...,1]) #three dots mean picking up everything

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 4 9], shape=(3,), dtype=int32)
tf.Tensor([2 2 7 3], shape=(4,), dtype=int32)
tf.Tensor([2 2 7 3], shape=(4,), dtype=int32)


In [103]:
tensor_three_d_index = tf.constant([
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
     [4,-3,32]],

])

print(tensor_three_d_index[0, :, :]) #first dimentsion, second dimension, third dimension
print(tensor_three_d_index[0, :, 1])
print(tensor_three_d_index[:, 1, :])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor(
[[ 3  5 -1]
 [ 1  0  2]
 [ 2  7  0]
 [ 4 -3 32]], shape=(4, 3), dtype=int32)
